"""Initial migration

Revision ID: 6349f0e48e35
Revises:
Create Date: 2025-11-04 17:17:02.559853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6349f0e48e35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Integer(), nullable=False),
    sa.Column('requires_keys', sa.Integer(), nullable=False),
    sa.Column('config_schema_json', sa.String(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )

    data_sources_table = sa.table('data_sources',
        sa.column('key', sa.String),
        sa.column('type', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('is_paid', sa.Integer),
        sa.column('requires_keys', sa.Integer),
        sa.column('enabled', sa.Integer)
    )

    op.bulk_insert(data_sources_table,
        [
            {'key': 'serpapi', 'type': 'job_discovery', 'name': 'SerpAPI', 'description': 'Google/Jobs search API', 'is_paid': 1, 'requires_keys': 1, 'enabled': 1},
            {'key': 'linkedin_scrape', 'type': 'job_discovery', 'name': 'LinkedIn Scrape', 'description': 'Headless browser scraping (use cautiously)', 'is_paid': 0, 'requires_keys': 0, 'enabled': 1},
            {'key': 'indeed_scrape', 'type': 'job_discovery', 'name': 'Indeed Scrape', 'description': 'Scrape job listings', 'is_paid': 0, 'requires_keys': 0, 'enabled': 1},
            {'key': 'company_site', 'type': 'job_discovery', 'name': 'Company Sites', 'description': 'Scrape company career pages', 'is_paid': 0, 'requires_keys': 0, 'enabled': 1},
            {'key': 'hunter', 'type': 'contact_discovery', 'name': 'Hunter.io', 'description': 'Email finder API', 'is_paid': 1, 'requires_keys': 1, 'enabled': 1},
            {'key': 'site_scrape_contacts', 'type': 'contact_discovery', 'name': 'Site Contact Scraper', 'description': 'Find emails on site/job page', 'is_paid': 0, 'requires_keys': 0, 'enabled': 1},
            {'key': 'neverbounce', 'type': 'validation', 'name': 'NeverBounce', 'description': 'Email validation', 'is_paid': 1, 'requires_keys': 1, 'enabled': 1},
            {'key': 'openai', 'type': 'parsing', 'name': 'OpenAI', 'description': 'Resume parsing using OpenAI API', 'is_paid': 1, 'requires_keys': 1, 'enabled': 1},
            {'key': 'gemini', 'type': 'parsing', 'name': 'Google Gemini', 'description': 'Resume parsing using Google Gemini API', 'is_paid': 1, 'requires_keys': 1, 'enabled': 1}
        ]
    )

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_json', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('since_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stats_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_template', sa.String(), nullable=False),
    sa.Column('body_template', sa.String(), nullable=False),
    sa.Column('is_system', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('storage_url', sa.String(), nullable=True),
    sa.Column('parsed_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('encrypted_token', sa.String(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_data_source_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Integer(), nullable=False),
    sa.Column('encrypted_credentials', sa.String(), nullable=True),
    sa.Column('config_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discovery_run_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('posting_url', sa.String(), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('max_per_hour', sa.Integer(), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validated', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('source_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sends')
    op.drop_table('contacts')
    op.drop_table('rate_limits')
    op.drop_table('job_postings')
    op.drop_table('user_data_source_configs')
    op.drop_table('suppressions')
    op.drop_table('senders')
    op.drop_table('resumes')
    op.drop_table('email_templates')
    op.drop_table('discovery_runs')
    op.drop_table('webhook_events')
    op.drop_table('users')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
